name: Python Package using Conda

on: [push]

defaults:
  run:
    shell: bash -el {0}

jobs:
  formatting:
    permissions:
      contents: read # for actions/checkout to fetch code
      pull-requests: write # for marocchino/sticky-pull-request-comment to create or update PR comment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: black
          create-args: black
          cache-environment: false

      - name: Check formatting
        run: black --check --diff .

  testing:
    runs-on: ubuntu-latest
    needs: formatting
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v4
      - name: Setup snakemke environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yaml
          environment-name: panaroo
          cache-environment: true
          init-shell: bash
      - name: Install post-deploy dependencies
        run: |
          EDLIB_USE_CYTHON=1 pip install --no-cache-dir edlib
      - name: Install pymummer from source
        run: |
          conda config --set channel_priority strict
          pip install -e tests

      - name: Install checks
        run: |
          pip install pytest
      - name: Test local
        env:
          CI: true
        run: |
          python -m pytest -vv

      - uses: jakebailey/pyright-action@v1
      - name: Test with pyright
        env:
          CI: true
        run: |
          pyright .
